### ISSUE TITLE
Can't save the database

### ISSUE THREAD

**Issue by akashnimare** [Belphemur/node-json-db#21]
I am getting this error - 

```
Uncaught Exception:
NestedError: Can't save the database
    at DatabaseError.Error (native)
    at DatabaseError.NestedError (/Users/akka/dev/zulipwork/zulip/dist/Zulip-darwin-x64/Zulip.app/Contents/Resources/app.asar/node_modules/node-json-db/lib/Errors.js:7:25)
    at new DatabaseError (/Users/akka/dev/zulipwork/zulip/dist/Zulip-darwin-x64/Zulip.app/Contents/Resources/app.asar/node_modules/node-json-db/lib/Errors.js:29:33)
    at JsonDB.save (/Users/akka/dev/zulipwork/zulip/dist/Zulip-darwin-x64/Zulip.app/Contents/Resources/app.asar/node_modules/node-json-db/JsonDB.js:243:25)
    at new JsonDB (/Users/akka/dev/zulipwork/zulip/dist/Zulip-darwin-x64/Zulip.app/Contents/Resources/app.asar/node_modules/node-json-db/JsonDB.js:33:18)
    at Object.<anonymous> (/Users/akka/dev/zulipwork/zulip/dist/Zulip-darwin-x64/Zulip.app/Contents/Resources/app.asar/app/main/main.js:16:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

I am using it [here](https://github.com/zulip/zulip-electron/search?utf8=%E2%9C%93&q=db). It works perfectly when app is not packed.

**Comment by Belphemur** [comment]
Hello @akashnimare 

The problem surely lies here: https://github.com/zulip/zulip-electron/blob/fc5b7324d2dc48849e32dc3404116fde1ecfbcc0/app/main/index.js#L16

By default, JsonDB (well OS in general) will open a file relatively to the working directory. When you're developing it's not a problem at all. However, if the user launching the app doesn't have "write access" to the working directory (usually where the app is installed) the OS is not going to let your write hence the error you're seeing.

Also, I have stricly no idea how the library act in a "browser". You should give it a full path with ``__dirname`` since it has not been made to work natively in browser.

**Comment by akashnimare** [comment]
@Belphemur so is there any way I can make it work. `node-json-db` is awesome but if I am not able to use in electron then surely I'll have to use some other db 😞 .

**Comment by Belphemur** [comment]
I'd say, give a full path.

Using https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname

And https://discuss.atom.io/t/open-external-file-with-electron/18569/7

You should be able to use the userData path for your database.

**Comment by akashnimare** [comment]
I can't make it work. I used this but no luck-

``` javascript
const data = db.getData(app.getPath('userData') + '/domain.json');
or
const data = db.getData(app.getAppPath() + '/domain.json');

```

**Comment by Belphemur** [comment]
Not when calling the getData. When initializing the database.

https://github.com/zulip/zulip-electron/blob/fc5b7324d2dc48849e32dc3404116fde1ecfbcc0/app/main/index.js#L16

```js
const db = new JsonDB(app.getPath('userData') + '/domain', true, true);
```

**Comment by akashnimare** [comment]
@Belphemur Thanks a lot it worked 🎉 .

**Comment by akashnimare** [comment]
@Belphemur hey, I'm getting this error again - 

![image](https://user-images.githubusercontent.com/2263909/31164510-2a24cc3e-a905-11e7-9e36-ed7e22e1c6a1.png)

This happens when the db file is empty. Is there any way to handle this?

**Comment by akashnimare** [comment]
@Belphemur I don't know why but sometimes the db file gets corrupted which results in https://github.com/Belphemur/node-json-db/issues/21#issuecomment-334074104. Do you know the possible reason behind this?

**Comment by Belphemur** [comment]
Do you have more than 1 instance of JsonDB on the same database at the 
same time ?

That really the only thing that I can think of that could corrupt the 
database. These instances would write a the same time on the same file.

**Comment by akashnimare** [comment]
I have only one instance of the db but I do reload the db file sometimes. Here is db file -
https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/utils/domain-util.js
Let me know if you find anything suspicious which might cause this issue. I have no clues here 😭 
(FYI only the `domain.json` file gets corrupted not others like `setting.json, window-state.json`)
