### ISSUE TITLE
TypeError: Config is not a constructor

### ISSUE THREAD

**Issue by WathikAhmed** [Belphemur/node-json-db#303]
Code
```
const JsonDB = require("node-json-db");
var Config = require("node-json-db/dist/lib/JsonDBConfig");

// The first argument is the database filename. If no extension, '.json' is assumed and automatically added.
// The second argument is used to tell the DB to save after each push
// If you put false, you'll have to call the save() method.
// The third argument is to ask JsonDB to save the database in an human readable format. (default false)
const db = new JsonDB(new Config("myDataBase", true, false, "/"));

// Pushing the data into the database
// With the wanted DataPath
// By default the push will override the old value
db.push("/test1", "super test");

// Get the data from the root
var data = db.getData("/");

// From a particular DataPath
var data = db.getData("/test1");
```
The command I used to run
`node .\dbSystem.js`  

Console output
```
D:\Desktop 2\GITHUB\nodejs-express\dbSystem.js:8
const db = new JsonDB(new Config("myDataBase", true, false, "/"));
                      ^

TypeError: Config is not a constructor
    at Object.<anonymous> (D:\Desktop 2\GITHUB\nodejs-express\dbSystem.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
PS D:\Desktop 2\GITHUB\nodejs-express> 
```

Any help is appreciated!

**Comment by Belphemur** [comment]
It looks like you're using an old way to import objects:

```typescript
import { JsonDB } from 'node-json-db';
import { Config } from 'node-json-db/dist/lib/JsonDBConfig'
```

This is the right way to do your imports, require method is deprecated.

If you still need to use the require method, this should do the trick.

```typescript
const JsonDB = require("node-json-db").JsonDB;
var Config = require("node-json-db/dist/lib/JsonDBConfig").Config;
```

**Comment by WathikAhmed** [comment]
Thanks.
