### ISSUE TITLE
Crashing when it can't find datapath.

### ISSUE THREAD

**Issue by DeveloperBen** [Belphemur/node-json-db#32]
When I run my code then it just crashes. I have it in a try loop which is why I don't understand why it 
crashes.
Code:
```
var bugIDcount = 1;
var continueWorking = true;
while (continueWorking) {
  console.log("In the loop again?");
  try {
    var data = bugs.getData(`/${bugIDcount}`);
  } catch (error) {
    console.error(error);
    continueWorking = false;
  }
  bugIDcount++;
}
```
Console Log:
```
  stack: 'NestedError: Can\'t find dataPath: /2. Stopped at 2
      at DataError.NestedError (/Users/Ben/git/crashlanding-discord/node_modules/node-json-db/lib/Errors.js:7:25)
          at new DataError (/Users/Ben/git/crashlanding-discord/node_modules/node-json-db/lib/Errors.js:37:33)
              at findData (/Users/Ben/git/crashlanding-discord/node_modules/node-json-db/JsonDB.js:100:27)
                  at recursiveProcessDataPath (/Users/Ben/git/crashlanding-discord/node_modules/node-json-db/JsonDB.js:127:17)
                      at JsonDB._getData (/Users/Ben/git/crashlanding-discord/node_modules/node-json-db/JsonDB.js:140:16)
                          at JsonDB.getData (/Users/Ben/git/crashlanding-discord/node_modules/node-json-db/JsonDB.js:70:21)
                              at Object.<anonymous> (/Users/Ben/git/crashlanding-discord/bot.js:27:21)
                                  at Module._compile (module.js:660:30)\n    at Object.Module._extensions..js (module.js:671:10)
                                      at Module.load (module.js:573:32)',
  message: 'Can\'t find dataPath: /2. Stopped at 2',
  inner: undefined,
  id: 5 }
```

**Comment by Belphemur** [comment]
Hello Ben,

You're trying to access to a key that doesn't exists.

You can only do a getData with a path that exists already in the "database".
