### ISSUE TITLE
No Longer Loading After V1.3.0

### ISSUE THREAD

**Issue by littlej247** [Belphemur/node-json-db#328]
My app has been using it since V1.1.0. After updating, it will not run on V1.4.1 or V1.4.0. 
**When using V1.3.0, it works fine.** 
Didn't notice anything in the changlog ( https://github.com/Belphemur/node-json-db/releases ) about it needing to be used differently. 

This is the error I'm getting.
```
node_modules/node-json-db/dist/JsonDB.js:13
    loaded = false;
           ^
SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (app/controller/app.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cSecure@1.0.0 controller: `DEBUG=CD*,-CD.message node --inspect=127.0.0.1:9223 ./controller/app.js`
npm ERR! Exit status 1
npm ERR!
```

This is how I'm loading it:
```
let JsonDB = require('node-json-db').JsonDB;
let Config = require('node-json-db/dist/lib/JsonDBConfig').Config;
global.config = new JsonDB(new Config(__dirname+"/config.json", true, true, '/'));
```

**Comment by Belphemur** [comment]
This looks like an issue with Node more than NodeJS.

I've dropped support for Node < 14.
