### ISSUE TITLE
Error on production server.

### ISSUE THREAD

**Issue by jamesxsc** [Belphemur/node-json-db#533]
Trying to use this library but getting the below syntax error:
```
Application has thrown an uncaught exception and is terminated:
C:\inetpub\ignite\node_modules\node-json-db\dist\JsonDB.js:15
    loaded = false;
           ^

SyntaxError: Unexpected token =
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\inetpub\ignite\ignite.js:1:88)
```
Any help much appreciated.
My imports are as below
```
const {JsonDB, Config} = require('node-json-db');
const express = require('express');
```

**Comment by Belphemur** [comment]
From the look of it you're running an old version of Node.
I'm only supporting Node >= 14
