### ISSUE TITLE
Arrays indexing fails with numeric keys

### ISSUE THREAD

**Issue by xrchz** [Belphemur/node-json-db#571]
There seem to be various problems with array processing:

```
> const db = new JsonDB(new Config('foo'))
undefined
> await db.push('/foo/1[]', 'hello')
undefined
> await db.push('/foo/1[]', 'world')
undefined
> await db.count('/foo/1')
2
> await db.getData('/foo/1[-1]')
'd'  // expected: 'world'
> await db.getData('/foo/1[1]')
'o' // expected: 'world'
> await db.getData('/foo/1[0]')
'w' // expected: 'hello'
> await db.getData('/foo/1')
[ 'hello', 'world' ]
> await db.push('/foo/2[]', {test: 1, baz: 2})
undefined
> await db.push('/foo/2[]', {test: 3, baz: 4})
undefined
> await db.count('/foo/2')
2
> await db.getData('/foo/2[-1]')
{ test: 3, baz: 4 }
> await db.getData('/foo/2[-2]')
Uncaught DataError: DataPath: /foo/2[-2]. . Can't find index -2 in array 2
    at recursiveProcessDataPath (node_modules/node-json-db/dist/JsonDB.js:88:27)
    at recursiveProcessDataPath (node_modules/node-json-db/dist/JsonDB.js:98:20)
    at JsonDB.retrieveData (node_modules/node-json-db/dist/JsonDB.js:103:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  inner: undefined,
  id: 10
} // expected: {test: 1, baz: 2}
```

**Comment by Belphemur** [comment]
Could you attach the resulting JSON file ?

This is indeed a curious behavior.

**Comment by xrchz** [comment]
It's as expected:
```
{"foo":{"1":["hello","world"],"2":[{"test":1,"baz":2},{"test":3,"baz":4}]}}
```
